AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hyphen NEW CRM Application
Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 60
    Layers:
    - Ref: AwsSdkLayer2
Parameters:
  StageName:
    Type: String
    Default: dev
Resources:
  AwsSdkLayer2:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AWS-SDK-Layer
      Description: Latest AWS SDK for Lambda
      ContentUri: s3://test-crm-new-2025/414abf1f7fc5c1236787bf9a5d80593c
      CompatibleRuntimes:
      - nodejs20.x
      LicenseInfo: Available under the MIT-0 license.
      RetentionPolicy: Delete
    Metadata:
      SamResourceId: AwsSdkLayer2
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 1028
      Timeout: 900
      Handler: test.main
      CodeUri: s3://test-crm-new-2025/911765311ccbb6d76de1edbf1469825d
    Metadata:
      SamResourceId: TestFunction
